server:
  port: 9527


eureka:
  client:
    register-with-eureka: true    #表识不向注册中心注册自己
    fetch-registry: true   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      # defaultZone: http://eureka7002.com:7002/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    hostname: gateway-service

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:                          #路由
        - id: hystrix_service          #路由的id 唯一 可随便 建议使用服务名
          uri: http://localhost:8009   #具体的服务的访问路径
          predicates:                  #断言 匹配上才会去访问相对应的服务 /** 代表匹配全部
            - Path=/hystrix/**
        - id: pay_service              #配置动态路由 通过服务名
          uri: lb://PAY-SERVICE        #直接写注册中心的服务名 lb代表负载均衡的规则-轮询规则
          predicates:
            - Path=/pay/**