server:
  port: 82

spring:
  application:
    name: feign-pay-service
  datasource:
    username: root
    password: Admin123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.130.191:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  #热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka